{% set name = "cliche" %}
{% set version = "0.6.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cliche-{{ version }}.tar.gz
  sha256: 1a7d0986b6d1840fb6423b84db76460eabd6ad671714f9ac86b123b3d9444fd2


build:
  number: 0
  noarch: python
  entry_points:
    - cliche = cliche.__init__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - cliche
  commands:
    - pip check
    - cliche --help
  requires:
    - pip

about:
  home: https://github.com/kootenpv/cliche
  summary: A minimalistic CLI wrapper out to be the best
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - kootenpv
